### ISSUE TITLE
afputils gif rendering

### ISSUE THREAD

**Issue by iamevn** [DragonMinded/bemaniutils#18]
Wondering if you have any thoughts/plans on handling gifs and if it's worth mentioning gif limitations in `afputils render -h`.

I was trying to render a gif for a pop'n animation with a transparent background and was surprised by it seeming to ignore the transparency I gave it. So I read up on how gifs work and there's some extra args for [Image.save](https://github.com/DragonMinded/bemaniutils/blob/b02c4292be869b3daa534de57b1fe7246e97068e/bemani/utils/afputils.py#L730): [transparency and disposal](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#saving)

Disposal is simple enough, `disposal=2` is what we want to start each frame as a clean slate. Transparency is not as simple. It's an index into the color palette for the frame indicating which color should be transparent. Generally this would mean having to pick a color not used in the animation being rendered, use that as the background (recomposite frames on to the colored background), convert from RGBS to P, and specify palettes for each frame which contain the transparent color at the same index. Usually the first entry (`transparency=0`) in the palettes PIL generates would be the right one (I assume because it's in the top left corner) but this probably isn't always the case.

As I was playing around with palette generation to try that out I quickly ran into the 256 colors per palette limit. I gave up here and just rendered to png frames and threw them at ffmpeg to make into a video.

**Comment by DragonMinded** [comment]
I spent a bit of time trying to get the gif renderer working well at the beginning but there were just too many limitations to do it well. For starters, there are many animations whose framerate is faster than gif can specify. When that happened, PIL would render very chunky animations that seemed to stutter and freeze on frames. It would only look good on simpler Pop'n animations that ran at around 24fps. The disposal issue is also concerning because it means that it would generate larger gif files instead of delta frames when animation changes only by a little. In theory, that could limit the number of colors as well but I'm not sure that is the case in practice? And finally, to be frank it should be on PIL to correctly specify a transparent frame when an RGBA image is converted to GIF/series of GIFs, but I guess we could try to work around that as well. All in all it didn't seem worth it to me so I render out to webp for my tests, and other people render out to PNG frames and export to their favorite animated format.

That said, I'm not against trying to improve the GIF rendering output, but it seems that PIL's GIF renderer is a bit immature to make reasonable images. Its probably worth leaving the issue open in case somebody wants to tackle it.

**Comment by DragonMinded** [comment]
I don't think anyone is going to take a stab at this, so I added a note discouraging .gif use in afputils and am closing this.
