### ISSUE TITLE
Sound Voltex III Mission support

### ISSUE THREAD

**Issue by EnderWolf53** [DragonMinded/bemaniutils#42]
I'm making a server for my SDVX III cabinet, i've created an admin account linked to a card and everything runs, scores are saved etc. but for some reason the missions that you normally get when playing online aren't showing up.
Does the server environment support SDVX III Missions ? If it does, how can i check the state of player missions ?

**Comment by DragonMinded** [comment]
You mean the mini-stories? No. There were some required server strings to make mission mode work properly and the networks that have them don't want them public. I'm not sure why, since all it would take is literally one one person connecting to any of those networks to save the logs of their play session to get the information, but that's the state of the community. So they should be turned off.

**Comment by EnderWolf53** [comment]
Are those strings about the BSS data or the blaster-like missions, i'm asking because while private networks are not the most accessible, i and some friends managed to obtain data from official servers in plain form (won't reveal how to avoid potential patching) so i have a pretty reliable way to get said strings.

**Comment by DragonMinded** [comment]
Wouldn't the strings be for a version that's several years old now, though? Support for SDVX III has been offline for about four years now. IIRC they were for the individual missions. I don't know what the BSS data is you refer to. Anyway, I've tried my best to keep this codebase free of any copyrighted content so I'm not sure what we could even do if we had the right data since it would be obtained from the official servers. I've had to turn down other stuff like this in the past due to the gray area it puts things in as well as the whole "you can have this but I don't want it public" thing.

**Comment by EnderWolf53** [comment]
SDVX III AC stopped being supported, but the servers are still active and used for SDVX Console (aka SDVX III PC).
BSS Refers to Battle Sequence System (the PvE parts).
As for implementing the missions, (i'm assuming we would use the existing DB), we could use the same method as saving scores, use dbutils to populate the DB using user-provided data.

**Comment by DragonMinded** [comment]
There's already robust infrastructure for handling things such as this. You would put the mission entries in the game's catalog, and you would use achievements to store their progress. The problem is that this isn't user-provided data. Its exfiltrated from official servers using an unknown exploit and I'm not sure I want to go down the path of having support for things like that. Most people setting up a server for themselves wouldn't be able to get ahold of the data as it stands.
