### ISSUE TITLE
How to run bemanishark on Windows?

### ISSUE THREAD

**Issue by RinChanNOWWW** [DragonMinded/bemaniutils#46]
I ran `bemanishark` on WSL but it could not capture the packets of the local server on Windows. I tried to run `bemanishark` on Windows, but the codes seem not support Windows.

**Comment by Subject38** [comment]
Since bemanishark uses socket features that are only provided by Linux, I don't think there's a way to run it without either modifying the source or porting it to a fiddler/wireshark plugin. Interestingly, it doesn't even work on MacOS because AF_PACKET is not a POSIX feature. Your best bet is to just run it in wsl instead and somehow route traffic through that...

**Comment by DragonMinded** [comment]
Unfortunately, yeah, `bemanishark` is pretty much linux-only and I don't know if that will ever change. It also had a longstanding bug where after awhile some TCP fragments would not get reassembled, and I don't know why. It appeared that linux stopped forwarding them, but I'm fairly sure its a bug in my own understanding of TCP itself.

Probably better is if you can, run `proxy` instead, point it at the server you wanted to sniff, and then point your game at proxy. It'll MITM all of the stuff for you and print logs. That should work on windows just fine. If you are attempting to sniff official traffic, that won't work with any tool since you need the white dongle SSL keys.

**Comment by RinChanNOWWW** [comment]
Thank you for answering my question. I'll try `proxy`.

**Comment by RinChanNOWWW** [comment]
Solved.
